#spring.application.name=oliveyoung

spring:
  datasource:
    url: jdbc:mysql://mysql.coffit.xyz:3322/olivedb
    username: olive
    password: olive
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 # 1시간 (밀리초)
  refresh-expiration: 1209600000 # 14일 (밀리초)
  header: Authorization
  prefix: Bearer

logging:
  level:
    org.springframework.security: DEBUG
